---
Name: 'dd-canonical'
After:
  - '*'
---
Page:
  extensions:
    - LoveDuckie\SilverStripe\Canonical\SiteTreeCanonicalExtension

LoveDuckie\SilverStripe\Canonical:
  use_page_link: false

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - LoveDuckie\SilverStripe\Canonical\ConfigCanonicalExtension
