---
Name: 'dd-canonical'
After:
  - '*'
---
Page:
  extensions:
    - LoveDuckie\SilverStripeCanonical\SiteTreeCanonicalExtension

LoveDuckie\SilverStripeCanonical:
  use_page_link: false

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - LoveDuckie\SilverstripeCanonical\ConfigCanonicalExtension
    